### ISSUE TITLE
Valid Unicode Characters Are Not Handled Correctly

### ISSUE THREAD

**Issue by cwildes** [CiscoTestAutomation/ncdiff#1]
In the following test the valid unicode character causes an exception in model.py:
11659: File "/ws/ranautiy-sjc/pytest1/lib/python3.6/site-packages/yang/ncdiff/model.py", line 555, in download
11660: f.write(reply.data)
11661: UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 813: ordinal not in range(128)

This code (the write is on line 555as complained about below):
 
        if reply.ok:
            fname = self.dir_yang + '/' + module + '.yang'
            with open(fname, 'w') as f:
                f.write(reply.data)
            self.downloaded.add(module)
 
…needs to be updated to be:
 
        if reply.ok:
            fname = self.dir_yang + '/' + module + '.yang'
            with open(fname, 'wb') as f:
                f.write(reply.data.encode('UTF-8'))
            self.downloaded.add(module)

There may be other places in the code that need to be modified to handle valid Unicode characters

**Comment by siming85** [comment]
@yuekyang  would you be able to take a look?

**Comment by siming85** [comment]
@cwildes can you open a PR on this?

**Comment by yuekyang** [comment]
@cwildes Thank you for bringing it up. It's fixed by commit https://github.com/CiscoTestAutomation/ncdiff/commit/6e068af0184e9ea912425323af1527c65cb9e3fc
