### ISSUE TITLE
validate_config() is not called

### ISSUE THREAD

**Issue by yuekyang** [CiscoTestAutomation/ncdiff#16]
When a ConfigDelta object is initiated by delta argument, non-presence containers are not cleaned in config_dst:

```
config1 = """
<nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <aaa>
      <new-model xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa"/>
      <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
        <policy>genericstring</policy>
        <lifetime>
          <day>15</day>
        </lifetime>
      </common-criteria>
      <session-id xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">common</session-id>
    </aaa>
  </native>
</nc:config>
"""

config2 = """
<nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <aaa>
      <new-model xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa"/>
      <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
        <policy>genericstring</policy>
      </common-criteria>
      <session-id xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">common</session-id>
    </aaa>
  </native>
</nc:config>
"""
edit_config = """
<nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <aaa>
      <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
        <policy>genericstring</policy>
        <lifetime>
          <day nc:operation="delete">15</day>
        </lifetime>
      </common-criteria>
    </aaa>
  </native>
</nc:config>
"""

c1 = Config(ncdevice=md, config=config1)
c2 = Config(ncdevice=md, config=config2)
delta = ConfigDelta(
  config_src=c1,
  delta=xml_.to_ele(edit_config),
)
print(delta.config_dst == c2)
delta.config_dst.validate_config()
print(delta.config_dst == c2)
```

The first print is False and the second is True. @wouterdb, why do we choose to skip validate_config()?
https://github.com/CiscoTestAutomation/ncdiff/blob/master/src/ncdiff/config.py#L115

Thanks,
Jonathan

**Comment by sjpatel21** [comment]
Hello Jonathan,

Can you please let me know which version of pyats you are using.
Please paste the output of the command `pyats version check`

Thank you

**Comment by wouterdb** [comment]
Hi Jonathan,

I don't have the correct yang schema's, so I can't reproduce this. Could you provide the config before and after validation?

If I remember correctly, (but this is a long time ago), I disabled validation by default because it is a slow process (if you have 30k+ lines of xml per device) and the config produced by the `NetconfCalculator` should be valid config.

So if the config coming out of the calculator is not valid, this is a bug in the `NetconfCalculator` in my opinion.

Wouter

**Comment by yuekyang** [comment]
Hi Wouter,

You have a good point. Current `NetconfCalculator` does not remove empty non-presence containers. I will work on it.

Jonathan

**Comment by yuekyang** [comment]
Fixed by commit https://github.com/CiscoTestAutomation/ncdiff/commit/1b7a580a5760668097a495f01da25b7b4b843332
