### ISSUE TITLE
Manually download YANG modules

### ISSUE THREAD

**Issue by dpeachey** [CiscoTestAutomation/ncdiff#17]
Hi,

For certain reasons, for example you cannot download the YANG modules from the device due to a vendor bug, you might like to manually populate the `./yang` folder with the modules yourself and do not try to download them from the device.

It is possible to pass an arbitrary value to `scan_models()` for the download parameter, like `scan_models(download='ignore')`, which will ignore downloading or checking YANG modules, but this is not documented and I guess not an 'official' way of doing it. Either `check` or `force` is expected.

Would it make sense to support this option and update the documentation?

Thanks,

Dan

**Comment by yuekyang** [comment]
This issue is resolved by https://github.com/CiscoTestAutomation/ncdiff/commit/7cba1c893905e1afeecfdebbb5a0187cb9ef2e44

`ignore` option is now supported in `scan_models()`

**Comment by yuekyang** [comment]
Document of `scan_models()` has been updated.
https://ncdiff.readthedocs.io/en/latest/api_device.html
