### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'host'

### ISSUE THREAD

**Issue by ajafferj** [CiscoTestAutomation/ncdiff#9]
Hi,

Using version 2.1.3

When i try to connect via ```manager.connect```:
test = manager.connect(host='192.168.0.99',
                            port='830',
                            username='ADMIN',
                            password='ADMIN',
                            hostkey_verify=False,
                            look_for_keys = False,
                            timeout=600)

I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 209, in <module>
    nc.connect()
  File "test.py", line 39, in connect
    timeout=600)
  File "/usr/local/lib/python3.6/site-packages/ncdiff/manager.py", line 54, in connect
    return ModelDevice(session, device_handler, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ncdiff/manager.py", line 98, in __init__
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'host'
```
When i remove **kwargs are a parameter in ModelDevice thats passed into NCCLIENT manager it works. 

Am i missing anything to get it working off the bat? calling NCCLIENT standalone works.

Thanks

**Comment by yuekyang** [comment]
Try the pre-release version:
`pip install ncdiff==20.5.1b0`

**Comment by tahigash** [comment]
no update on this issue for long time. I'm closing issue. please feel free to reopen if you still have same issue with latest package.
